*** adding-a-database-to-the-django-project-using-sqlite3-with-python-2-7 ***

 I am trying to add a database to the Django Project using Sqlite3 and Python 2.7.  
 This is how my setting.py looks like: 
 
 It allows me to create the database and it asks me to create the superuser: 
 
 When i type yes, it gives me this error msg. 
 Error msg: 
 
 How do i solve the error above? Why doesn't it allow me to add a superuser? what should i do? Could this problem because I am running Python 2.7? 
 
 Type this before you execute the python manage.py syncdb 
 
 This will solve the error.. Btw i was using mac os x python which was in /usr/bin/python. 
 Add it to the ./.bash_profile file so that it calls it automatically.. 
 
 I actually ran into this on windows recently. This is a hack, not a fix or an answer, but it might get you through your problem: 
 Put this at the top of your manage.py script 
 
 http://keeyai.com/2012/02/17/django-deployment-create-superuser-fails-with-locale-error/ 
 