*** an-error-occurred-while-updating-the-entries-see-the-inner-exception-for-detail ***

 
 
 
 
 
 
 
 
                            It's difficult to tell what is being asked here. This question is ambiguous, vague, incomplete, overly broad, or rhetorical and   cannot be reasonably answered in its current form. For help clarifying this question so that it can be reopened,    visit the help center .
                            
                         
 
 
 Closed  6 years ago . 
 
 
 When i delete an item in a listbox, i get the error in the question as shown in the screenshot below:
 
 I do not know where the inner exception is, but i tried try, catch but i got the same error in the question. 
 Here is all of the code : 
 
 
 Click "View Detail..." a window will open where you can expand the "Inner Exception" my guess is that when you try to delete the record there is a reference constraint violation.  The inner exception will give you more information on that so you can modify your code to remove any references prior to deleting the record. 
 
 
 Click "view details" to find the inner exception. 
 