*** django-error-matching-query-does-not-exist ***

 I finally released my project to the production level and suddenly I have some issues I never had to deal with in the development phase. 
 When the users posts some actions, I sometimes get the following error. 
 
 What really frustrates me is that the project works fine in the local environment and furthermore, the matching query object DOES exist in the Database. 
 Now I am suspecting that the user is accessing the Database when it's reserved to other users, but there's no way to prove my argument nor I have any solution to it. 
 Does anybody had this kind of issue before? Any suggestions on how to resolve this issue? 
 Thank you very much for your help in advance. 
 EDIT: I have manually queried the database using the same information retrieved from the server error email I received. I was able to hit the entry without any issue. Furthermore, it seems like the exact same behavior the user performed does not raise any issue most of the time, but rather in some (which is yet unknown) cases. In conclusion, it definitely is not an issue with the missing entry in the database.  
 
 your line raising the error is here: 
 
 you try to access a non-existing comment. 
 
 Instead of having an error on your server, your user will get a 404 meaning that he tries to access a non existing resource. 
 Ok up to here I suppose you are aware of this. 
 Some users (and I'm part of them) let tabs running for long time, if users are authorized to delete data, it may happens. A 404 error may be a better error to handle a deleted resource error than sending an email to the admin. 
 Other users go to addresses from their history, (same if data have been deleted since it may happens). 
 
 Maybe you have no Comments record with such primary key, then you should use this code: 
 
 
 You can use this: 
 
 
 You may try this way. just use a function to get your object 
 
 