*** in-sqlalchemy-how-do-i-create-a-foreignkey-relationship-across-2-different-py ***

 In  , I have this: 
 
 When I run this, I create a user table. 
 On my other file,  , I have this: 
 
 So, as you can see, I want to put a many-to-one relationship from groups -> users. 
 But when I run  ...I get this error: 
 
 If I put the two tables together in one file, I'm sure it could work...but because I split it into 2 files (which I absolutely have to)...I don't know how to make ForeignKey relationships work anymore? 
 
 The key is to use the same Base for both foreign keys, instead of creating a new one for each table. 
 basetest.py 
 
 
 
 
 
 Make sure that you have same   to create all related tables. 
 